import SwiftUI
import UIKit

struct ActivityView: UIViewControllerRepresentable {
    let items: [Any]

    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}

enum RequestSharing {
    static func text(for needs: [ClassroomNeed], teacherName: String) -> String {
        guard !needs.isEmpty else {
            return "Support local classrooms with Refill."
        }
        let lines = needs.prefix(5).map { need in
            let remaining = need.amountRemaining.formatted(.currency(code: "USD").precision(.fractionLength(0)))
            return "• \(need.title) — \(remaining) remaining"
        }
        return (["Help \(teacherName)'s classroom refill:"] + lines).joined(separator: "\n")
    }
}

enum RequestPDFExporter {
    static func export(needs: [ClassroomNeed], profile: Profile) throws -> URL {
        guard !needs.isEmpty else { throw ExportError.noRequests }

        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("RefillExports", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appendingPathComponent("Refill-Classroom-Requests-\(UUID().uuidString.prefix(8)).pdf")

        let page = CGRect(x: 0, y: 0, width: 612, height: 792)
        let renderer = UIGraphicsPDFRenderer(bounds: page)
        try renderer.writePDF(to: url) { context in
            for need in needs {
                context.beginPage()
                draw(need: need, profile: profile, in: page)
            }
        }
        return url
    }

    private static func draw(need: ClassroomNeed, profile: Profile, in page: CGRect) {
        let margin: CGFloat = 48
        let width = page.width - margin * 2
        var y = margin

        y += drawText("REFILL · CLASSROOM REQUEST", at: CGPoint(x: margin, y: y), width: width,
                      font: .systemFont(ofSize: 12, weight: .bold), color: UIColor.systemBlue)
        y += 16
        y += drawText(need.title, at: CGPoint(x: margin, y: y), width: width,
                      font: .systemFont(ofSize: 25, weight: .bold), color: .label)
        y += 12
        let teacher = profile.fullName.isEmpty ? need.teacherName : profile.fullName
        let school = profile.schoolName.isEmpty ? need.schoolName : profile.schoolName
        y += drawText("\(teacher) · \(school) · \(need.city)", at: CGPoint(x: margin, y: y), width: width,
                      font: .systemFont(ofSize: 13, weight: .semibold), color: .secondaryLabel)
        y += 24
        y += drawText("Request", at: CGPoint(x: margin, y: y), width: width,
                      font: .systemFont(ofSize: 16, weight: .bold), color: .label)
        y += 6
        y += drawText(need.rawRequest, at: CGPoint(x: margin, y: y), width: width,
                      font: .systemFont(ofSize: 14), color: .label)
        y += 22
        y += drawText("Itemized supplies", at: CGPoint(x: margin, y: y), width: width,
                      font: .systemFont(ofSize: 16, weight: .bold), color: .label)
        y += 8
        for item in need.items.prefix(10) {
            let amount = item.total.formatted(.currency(code: "USD"))
            y += drawText("\(item.quantity) × \(item.name) — \(amount)", at: CGPoint(x: margin, y: y), width: width,
                          font: .systemFont(ofSize: 13), color: .label)
            y += 5
        }
        y += 18
        let goal = need.fundingGoal.formatted(.currency(code: "USD"))
        let raised = need.raised.formatted(.currency(code: "USD"))
        y += drawText("Funding goal: \(goal) · Raised: \(raised)", at: CGPoint(x: margin, y: y), width: width,
                      font: .systemFont(ofSize: 15, weight: .bold), color: .label)
        y += 18
        if !need.aiSummary.isEmpty {
            _ = drawText("Refill summary: \(need.aiSummary)", at: CGPoint(x: margin, y: y), width: width,
                         font: .italicSystemFont(ofSize: 13), color: .secondaryLabel)
        }

        _ = drawText("Generated by Refill · Verify current availability before funding.",
                     at: CGPoint(x: margin, y: page.height - 64), width: width,
                     font: .systemFont(ofSize: 10), color: .tertiaryLabel)
    }

    @discardableResult
    private static func drawText(
        _ text: String,
        at point: CGPoint,
        width: CGFloat,
        font: UIFont,
        color: UIColor
    ) -> CGFloat {
        let paragraph = NSMutableParagraphStyle()
        paragraph.lineBreakMode = .byWordWrapping
        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: color,
            .paragraphStyle: paragraph
        ]
        let bounding = (text as NSString).boundingRect(
            with: CGSize(width: width, height: .greatestFiniteMagnitude),
            options: [.usesLineFragmentOrigin, .usesFontLeading],
            attributes: attributes,
            context: nil
        )
        (text as NSString).draw(in: CGRect(x: point.x, y: point.y, width: width, height: ceil(bounding.height)), withAttributes: attributes)
        return ceil(bounding.height)
    }

    enum ExportError: LocalizedError {
        case noRequests
        var errorDescription: String? { "Create a classroom request before exporting a PDF." }
    }
}
